### ISSUE TITLE
Why IReviewItem need to have ReviewOutcome property?

### ISSUE THREAD

**Issue by afucher** [helephant/SpacedRepetition.Net#4]
Hi,
this is more a question than an issue :) 

I was navigating throught the code, and didn't understand why the IReviewItem need to have the ReviewOutcome property.

Is this really necessary?

**Comment by helephant** [comment]
Good point, you're right that it's not necessary. It can be inferred from CorrectReviewStreak and is not used by the SuperMemo. I've removed it from IReviewItem and ReviewItem, updated the tests and update the package.
